import os
import click
from pathlib import Path

@click.command()
@click.argument("name")
def new(name: str) -> None:
    """Create a new Moxie project scaffold."""
    project_dir = Path(name)
    if project_dir.exists():
        click.echo(f"Error: Directory '{name}' already exists.")
        return

    click.echo(f"🚀 Creating new Moxie project: {name}")
    
    # Create directory structure
    dirs = [
        project_dir / "app",
        project_dir / "app/routes",
        project_dir / "app/models",
        project_dir / "tests",
    ]
    
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        (d / "__init__.py").touch()

    # Create main.py
    main_py = project_dir / "app/main.py"
    main_py.write_text("""from moxie import Moxie

app = Moxie(
    title="New Moxie Project",
    description="Generated by Moxie CLI",
    version="0.1.0"
)

@app.get("/")
async def root():
    return {"message": "Hello from Moxie!"}
""")

    # Create pyproject.toml
    pyproject_toml = project_dir / "pyproject.toml"
    pyproject_toml.write_text(f"""[project]
name = "{name}"
version = "0.1.0"
dependencies = [
    "moxie-api",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
""")

    # Create .env
    (project_dir / ".env").write_text("DEBUG=true\n")

    click.echo(f"✅ Project '{name}' created successfully!")
    click.echo(f"\nNext steps:\n  cd {name}\n  pip install .\n  moxie dev app.main:app")
